<!DOCTYPE html>
<html lang="zh-Hant-TW">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>

  <body>
    <script>
      // ## Async 與 Promise
      // 定義的 Promise 函式
      // function promiseFn(num, time = 500) {
      //   return new Promise((resolve, reject) => {
      //     setTimeout(() => {
      //       num ? resolve(`${num}, 成功 `) : reject(' 失敗 ');
      //     }, time);
      //   });
      // }
      // // 呼叫 Promise 函式
      // promiseFn(1)
      //   .then(res => {
      //     console.log(res); // 1, 成功
      //     return promiseFn(2); // 鏈接第二次的 Promise 方法
      //   })
      //   .then(res => {
      //     console.log(res); // 2, 成功
      //   });


      // async function getData() {
      //   const data1 = await promiseFn(1); // 因為 await,promise 函式被中止直到回傳
      //   const data2 = await promiseFn(2);
      //   console.log(data1, data2); // 1, 成功 2, 成功
      // }
      // getData();


      // ## Async Function 就是 Promise
      // async function asyncFn() {
      //   return 'a';
      // }
      // console.log(asyncFn());


      // asyncFn().then(r => {
      //   console.log(r)
      // });


      // await 1;
      // Uncaught SyntaxError: await is only valid in async function


      // async function getData() {
      //   const data1 = await 1;
      //   const data2 = await promiseFn(2);
      //   console.log(data1, data2); // 1 "2, 成功 "
      // }
      // getData();


      // ## 47 Async 函式如何捕捉錯誤
      // promiseFn(1)
      //   .then(res => {
      //     console.log(res);
      //     return promiseFn(0);
      //   })
      //   .then(res => {
      //     console.log(res)
      //   })
      //   .catch(err => {
      //     console.log(err)
      //   });


      // async function getData2() {
      //   const data1 = await promiseFn(1);
      //   const data2 = await promiseFn(0);
      //   // Uncaught (in promise) 失敗
      //   console.log(data1, data2);
      // }
      // getData2();


      // async function getData2() {
      //   try { // 專注在成功
      //     const data1 = await promiseFn(1);
      //     const data2 = await promiseFn(0);
      //     console.log(data1, data2);
      //   }
      //   catch (err) { // 專注在錯誤
      //     console.log('catch', err);
      //   }
      // }
      // getData2();


      // ## 48 Async 函式如何同時發出請求、又如何依序執行多個陣列請求
      // async function promiseAll() {
      //   const data = await Promise.all([promiseFn(1, 3000), promiseFn(2)]);
      //   console.log(data)
      // }
      // promiseAll(); // ["1, 成功 ", "2, 成功 "]


      // const arrayData = [{ num: 1, time: 500 },
      // { num: 2, time: 3000 },
      // { num: 3, time: 1500 },
      // { num: 4, time: 1000 }
      // ];


      // async function seriesFn() {
      //   const data = [];
      //   // 依序執行,每一個請求都會有所延遲
      //   for (let i = 0; i < arrayData.length; i++) {
      //     const item = arrayData[i];
      //     data.push(await promiseFn(item.num, item.time));
      //     console.log(item.num, ' 執行完畢 ')
      //   }
      //   // 最後 console 可以列出所有值
      //   console.log(data); // ["1, 成功 ", "2, 成功 ", "3, 成功 ", "4, 成功 "]
      // }
      // seriesFn();


      // ## 小節測驗
      // ## 1. 請問以下執行後 res 的值為?
      // async function asyncFn() {
      //   const res = fetch('https://randomuser.me/api/');
      //   console.log(res);
      // }
      // asyncFn();
    </script>
  </body>

</html>